#!/bin/bash
#SBATCH --job-name="EQUIL_HMR"
#SBATCH --output="/expanse/lustre/projects/iit127/fcetin/5ht2b/logs/equil_hmr/EQUIL_HMR.%j.%N.out"
#SBATCH --partition=gpu-shared
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=8G
#SBATCH --account=iit127
#SBATCH -t 6:00:00

# Args: $1 input_dir  $2 name  $3 hmr_xml_dir  $4 output_root  $5 lig_resname  $6 dt_fs

source ~/.bashrc

conda activate prep1

cd /home/fcetin/MotorRow

echo "EQUIL_HMR BATCH JOB FOR $2  dt=$6 fs"
python RUN_CHIMPSS_MOTORROW.py "$1" "$2" "$3" "$4" --lig_resname "$5" --dt "$6"
